# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

from ccxt.base.exchange import Exchange
from ccxt.abstract.bitpandafusion import ImplicitAPI
from ccxt.base.types import Balances, Currencies, CurrencyInterface, Int, Market, Num, Order, OrderBook, OrderSide, OrderType, Str, Strings, Ticker, Tickers, Trade, TradingFeeInterface, TradingFees
from ccxt.base.errors import ExchangeError
from ccxt.base.errors import AuthenticationError
from ccxt.base.errors import PermissionDenied
from ccxt.base.errors import BadRequest
from ccxt.base.errors import BadSymbol
from ccxt.base.errors import InvalidOrder
from ccxt.base.errors import OrderNotFound
from ccxt.base.errors import NotSupported
from ccxt.base.errors import RateLimitExceeded
from ccxt.base.decimal_to_precision import TICK_SIZE
from ccxt.base.precise import Precise


class bitpandafusion(Exchange, ImplicitAPI):

    def describe(self) -> object:
        return self.deep_extend(super(bitpandafusion, self).describe(), {
            'id': 'bitpandafusion',
            'name': 'Bitpanda Fusion',
            'countries': ['AT'],
            'version': 'v1',
            'rateLimit': 250,
            'certified': False,
            'pro': False,
            'has': {
                'CORS': None,
                'spot': True,
                'margin': False,
                'swap': False,
                'future': False,
                'option': False,
                'cancelOrder': True,
                'createMarketBuyOrderWithCost': True,
                'createMarketOrderWithCost': True,
                'createMarketSellOrderWithCost': True,
                'createOrder': True,
                'createStopLimitOrder': True,
                'createStopMarketOrder': True,
                'createStopOrder': True,
                'createTriggerOrder': True,
                'fetchBalance': True,
                'fetchClosedOrders': True,
                'fetchCurrencies': True,
                'fetchMarkets': True,
                'fetchMyTrades': True,
                'fetchOHLCV': True,
                'fetchOpenOrders': True,
                'fetchOrder': True,
                'fetchOrderBook': True,
                'fetchOrders': True,
                'fetchTicker': True,
                'fetchTickers': True,
                'fetchTime': True,
                'fetchTrades': False,
                'fetchTradingFee': True,
                'fetchTradingFees': True,
                'ws': False,
            },
            'timeframes': {
                '1m': '1m',
                '5m': '5m',
                '10m': '10m',
                '15m': '15m',
                '30m': '30m',
                '1h': '1h',
                '4h': '4h',
                '1d': '1d',
            },
            'urls': {
                'api': {
                    'public': 'https://api.fusion.bitpanda.com',
                    'private': 'https://api.fusion.bitpanda.com',
                },
                'www': 'https://www.bitpanda.com/fusion',
                'doc': 'https://docs.fusion.bitpanda.com/',
            },
            'api': {
                'public': {
                    'get': {
                        'v1/time': {'cost': 1},
                        'v1/tickers': {'cost': 1},
                        'v1/pairs': {'cost': 1},
                        'v1/orderbook/{pair}': {'cost': 1},
                        'v1/candles/{pair}': {'cost': 1},
                        'v1/assets': {'cost': 1},
                    },
                },
                'private': {
                    'get': {
                        'v1/account': {'cost': 1},
                        'v1/account/balances': {'cost': 1},
                        'v1/account/orders': {'cost': 1},
                        'v1/account/orders/{orderId}': {'cost': 1},
                        'v1/account/trades': {'cost': 1},
                        'v1/account/trades/{tradeId}': {'cost': 1},
                    },
                    'post': {
                        'v1/account/orders': {'cost': 1},
                    },
                    'delete': {
                        'v1/account/orders/{orderId}': {'cost': 1},
                    },
                },
            },
            'httpExceptions': {
                '401': AuthenticationError,
                '403': PermissionDenied,
                '404': ExchangeError,
                '409': InvalidOrder,
                '422': BadRequest,
                '429': RateLimitExceeded,
            },
            'precisionMode': TICK_SIZE,
            'requiredCredentials': {
                'apiKey': True,
                'secret': False,
            },
            'features': {
                'spot': {
                    'sandbox': False,
                    'createOrder': {
                        'marginMode': False,
                        'triggerPrice': True,
                        'triggerPriceType': None,
                        'triggerDirection': False,
                        'stopLossPrice': False,
                        'takeProfitPrice': False,
                        'attachedStopLossTakeProfit': None,
                        'timeInForce': {
                            'IOC': True,
                            'FOK': True,
                            'PO': False,
                            'GTD': True,
                        },
                        'hedged': False,
                        'trailing': False,
                        'leverage': False,
                        'marketBuyByCost': True,
                        'marketBuyRequiresPrice': False,
                        'selfTradePrevention': False,
                        'iceberg': False,
                    },
                    'fetchMyTrades': {
                        'marginMode': False,
                        'limit': 100,
                        'daysBack': None,
                        'untilDays': None,
                        'symbolRequired': False,
                    },
                    'fetchOrder': {
                        'marginMode': False,
                        'trigger': False,
                        'trailing': False,
                        'symbolRequired': False,
                    },
                    'fetchOpenOrders': {
                        'marginMode': False,
                        'limit': 100,
                        'trigger': False,
                        'trailing': False,
                        'symbolRequired': False,
                    },
                    'fetchOrders': {
                        'marginMode': False,
                        'limit': 100,
                        'daysBack': None,
                        'untilDays': None,
                        'trigger': False,
                        'trailing': False,
                        'symbolRequired': False,
                    },
                    'fetchClosedOrders': {
                        'marginMode': False,
                        'limit': 100,
                        'daysBack': None,
                        'daysBackCanceled': None,
                        'untilDays': None,
                        'trigger': False,
                        'trailing': False,
                        'symbolRequired': False,
                    },
                    'fetchOHLCV': {
                        'limit': 1440,
                    },
                },
            },
        })

    def fetch_time(self, params={}) -> Int:
        """
        fetches the current integer timestamp in milliseconds from the exchange server

        https://docs.fusion.bitpanda.com/get-server-time-4295526e0

        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns int: the current integer timestamp in milliseconds from the exchange server
        """
        response = self.publicGetV1Time(params)
        return self.safe_integer(response, 'epochMs')

    def fetch_markets(self, params={}) -> list[Market]:
        """
        retrieves data on all markets for Bitpanda Fusion

        https://docs.fusion.bitpanda.com/get-trading-pairs-4295528e0

        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict[]: an array of objects representing market data
        """
        response = self.publicGetV1Pairs(params)
        return self.parse_markets(response)

    def parse_market(self, market: dict) -> Market:
        """
 @ignore
        parses an exchange market into a CCXT market structure
        :param dict market: exchange market
        :returns dict: a CCXT market structure
        """
        id = self.safe_string(market, 'pair')
        baseId = self.safe_string(market, 'baseAsset')
        quoteId = self.safe_string(market, 'quoteAsset')
        base = self.safe_currency_code(baseId)
        quote = self.safe_currency_code(quoteId)
        return self.safe_market_structure({
            'id': id,
            'symbol': base + '/' + quote,
            'base': base,
            'quote': quote,
            'settle': None,
            'baseId': baseId,
            'quoteId': quoteId,
            'settleId': None,
            'type': 'spot',
            'spot': True,
            'margin': False,
            'swap': False,
            'future': False,
            'option': False,
            'active': True,
            'contract': False,
            'linear': None,
            'inverse': None,
            'contractSize': None,
            'expiry': None,
            'expiryDatetime': None,
            'strike': None,
            'optionType': None,
            'precision': {
                'amount': self.safe_number(market, 'sizeIncrement'),
                'price': self.safe_number(market, 'tickSize'),
                'cost': self.safe_number(market, 'amountIncrement'),
            },
            'limits': {
                'leverage': {
                    'min': None,
                    'max': None,
                },
                'amount': {
                    'min': None,
                    'max': self.safe_number(market, 'maxOrderSize'),
                },
                'price': {
                    'min': None,
                    'max': None,
                },
                'cost': {
                    'min': self.safe_number(market, 'minOrderAmount'),
                    'max': self.safe_number(market, 'maxOrderAmount'),
                },
            },
            'created': None,
            'info': market,
        })

    def fetch_currencies(self, params={}) -> Currencies:
        """
        fetches all available currencies on Bitpanda Fusion

        https://docs.fusion.bitpanda.com/get-assets-4295529e0

        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: an associative dictionary of currencies
        """
        response = self.publicGetV1Assets(params)
        result = {}
        for i in range(0, len(response)):
            currency = self.parse_currency(response[i])
            result[currency['code']] = currency
        return result

    def parse_currency(self, currency: dict) -> CurrencyInterface:
        """
 @ignore
        parses an exchange currency into a CCXT currency structure
        :param dict currency: exchange currency
        :returns dict: a CCXT currency structure
        """
        id = self.safe_string(currency, 'symbol')
        code = self.safe_currency_code(id)
        return self.safe_currency_structure({
            'id': id,
            'code': code,
            'precision': None,
            'type': self.safe_string(currency, 'type'),
            'name': self.safe_string(currency, 'name'),
            'active': True,
            'deposit': None,
            'withdraw': None,
            'fee': None,
            'limits': {
                'deposit': {
                    'min': None,
                    'max': None,
                },
                'withdraw': {
                    'min': None,
                    'max': None,
                },
            },
            'networks': {},
            'info': currency,
        })

    def parse_ticker(self, ticker: dict, market: Market = None) -> Ticker:
        """
 @ignore
        parses a ticker from the exchange
        :param dict ticker: exchange ticker
        :param dict [market]: market structure
        :returns dict: a CCXT ticker structure
        """
        marketId = self.safe_string(ticker, 'pair')
        resolvedMarket = self.safe_market(marketId, market)
        return self.safe_ticker({
            'symbol': resolvedMarket['symbol'],
            'timestamp': None,
            'datetime': None,
            'high': self.safe_string(ticker, 'high'),
            'low': self.safe_string(ticker, 'low'),
            'bid': None,
            'bidVolume': None,
            'ask': None,
            'askVolume': None,
            'vwap': None,
            'open': None,
            'close': None,
            'last': self.safe_string(ticker, 'price'),
            'previousClose': None,
            'change': None,
            'percentage': None,
            'average': None,
            'baseVolume': None,
            'quoteVolume': None,
            'info': ticker,
        }, resolvedMarket)

    def fetch_ticker(self, symbol: str, params={}) -> Ticker:
        """
        fetches a price ticker, whose last field contains Bitpanda Fusion's documented current mid price

        https://docs.fusion.bitpanda.com/get-tickers-4295527e0

        :param str symbol: unified symbol of the market to fetch the ticker for
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: a ticker structure
        """
        self.load_markets()
        market = self.market(symbol)
        request = {
            'pair': market['id'],
        }
        response = self.publicGetV1Tickers(self.extend(request, params))
        ticker = self.safe_dict(response, 0, {})
        return self.parse_ticker(ticker, market)

    def fetch_tickers(self, symbols: Strings = None, params={}) -> Tickers:
        """
        fetches price tickers, whose last fields contain Bitpanda Fusion's documented current mid prices

        https://docs.fusion.bitpanda.com/get-tickers-4295527e0

        :param str[] [symbols]: unified symbols of the markets to fetch tickers for
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: a dictionary of ticker structures indexed by market symbols
        """
        self.load_markets()
        request = {}
        if symbols is not None:
            marketIds = self.market_ids(symbols)
            request['pair'] = ','.join(marketIds)
        response = self.publicGetV1Tickers(self.extend(request, params))
        return self.parse_tickers(response, symbols)

    def fetch_order_book(self, symbol: str, limit: Int = None, params={}) -> OrderBook:
        """
        fetches information on open orders with bid and ask prices, volumes and other data

        https://docs.fusion.bitpanda.com/get-orderbook-4205406e0

        :param str symbol: unified symbol of the market to fetch the order book for
        :param int [limit]: the maximum number of order book entries to return, between 1 and 100
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: an order book structure
        """
        self.load_markets()
        market = self.market(symbol)
        request = {
            'pair': market['id'],
        }
        if limit is not None:
            request['depth'] = limit
        response = self.publicGetV1OrderbookPair(self.extend(request, params))
        timestamp = self.parse8601(self.safe_string(response, 'timestamp'))
        return self.parse_order_book(response, market['symbol'], timestamp, 'bids', 'asks', 'price', 'quantity')

    def parse_ohlcv(self, ohlcv: dict, market: Market = None) -> list:
        """
 @ignore
        parses an OHLCV entry from the exchange
        :param dict ohlcv: exchange OHLCV entry
        :param dict [market]: market structure
        :returns dict: a CCXT OHLCV structure
        """
        seconds = self.safe_string(ohlcv, 'timestamp')
        timestamp = self.parse_to_int(Precise.string_mul(seconds, '1000'))
        return [
            timestamp,
            self.safe_number(ohlcv, 'open'),
            self.safe_number(ohlcv, 'high'),
            self.safe_number(ohlcv, 'low'),
            self.safe_number(ohlcv, 'close'),
            self.safe_number(ohlcv, 'volume'),
        ]

    def fetch_ohlcv(self, symbol: str, timeframe='1m', since: Int = None, limit: Int = None, params={}) -> list[list]:
        """
        fetches historical candlestick data containing the open, high, low, close price, and the volume of a market

        https://docs.fusion.bitpanda.com/get-candles-4311313e0

        :param str symbol: unified symbol of the market to fetch OHLCV data for
        :param str timeframe: the length of time each candle represents
        :param int [since]: timestamp in ms of the earliest candle to fetch
        :param int [limit]: the maximum number of candles to return, between 1 and 1440
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict[]: a list of OHLCV candle structures
        """
        self.load_markets()
        market = self.market(symbol)
        request = {
            'pair': market['id'],
            'interval': self.safe_string(self.timeframes, timeframe, timeframe),
        }
        if since is not None:
            sinceSeconds = self.parse_to_int(Precise.string_div(self.number_to_string(since), '1000'))
            if limit is None:
                request['from'] = sinceSeconds
            else:
                duration = self.parse_timeframe(timeframe)
                span = Precise.string_mul(self.number_to_string(duration), self.number_to_string(limit))
                request['to'] = self.parse_to_int(Precise.string_add(self.number_to_string(sinceSeconds), span))
        if limit is not None:
            request['limit'] = limit
        response = self.publicGetV1CandlesPair(self.extend(request, params))
        return self.parse_ohlcvs(response, market, timeframe, since, limit)

    def fetch_balance(self, params={}) -> Balances:
        """
        query for balance and get the amount of funds available for trading or funds locked in orders

        https://docs.fusion.bitpanda.com/get-account-balances-4204527e0

        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: a balance structure
        """
        self.load_markets()
        response = self.privateGetV1AccountBalances(params)
        result = {
            'info': response,
        }
        for i in range(0, len(response)):
            balance = response[i]
            currencyId = self.safe_string(balance, 'symbol')
            code = self.safe_currency_code(currencyId)
            free = self.safe_string(balance, 'available')
            used = self.safe_string(balance, 'locked')
            if code is not None:
                result[code] = {
                    'free': self.parse_number(free),
                    'used': self.parse_number(used),
                    'total': self.parse_number(Precise.string_add(free, used)),
                }
        return self.safe_balance(result)

    def parse_trading_fee(self, fee: dict, market: Market = None) -> TradingFeeInterface:
        """
 @ignore
        parses the uniform account fee into a CCXT trading fee structure. The live API returns camelCase fields and a decimal fee rate for QuoteCurrency mode, while the documented legacy response uses snake_case fields and a percentage value.
        :param dict fee: exchange account response
        :param dict [market]: unified market structure
        :returns dict: a CCXT trading fee structure
        """
        tier = self.safe_dict_2(fee, 'currentTier', 'current_tier', {})
        feeString = self.safe_string(tier, 'fee')
        feeMode = self.safe_string_lower_2(tier, 'feeMode', 'fee_mode')
        feeRate = self.parse_number(feeString)
        if feeMode == 'percentage':
            feeRate = self.parse_number(Precise.string_div(feeString, '100'))
        return {
            'info': fee,
            'symbol': None if (market is None) else market['symbol'],
            'maker': feeRate,
            'taker': feeRate,
            'percentage': True,
            'tierBased': True,
        }

    def fetch_trading_fee(self, symbol: str, params={}) -> TradingFeeInterface:
        """
        fetches the account's trading fee for a market

        https://docs.fusion.bitpanda.com/get-account-4295525e0

        :param str symbol: unified market symbol
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: a trading fee structure
        """
        self.load_markets()
        market = self.market(symbol)
        response = self.privateGetV1Account(params)
        return self.parse_trading_fee(response, market)

    def fetch_trading_fees(self, params={}) -> TradingFees:
        """
        fetches the account's uniform trading fee for all markets

        https://docs.fusion.bitpanda.com/get-account-4295525e0

        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: a dictionary of trading fee structures indexed by market symbols
        """
        self.load_markets()
        response = self.privateGetV1Account(params)
        fee = self.parse_trading_fee(response)
        result = {}
        for i in range(0, len(self.symbols)):
            symbol = self.symbols[i]
            result[symbol] = self.extend({}, fee, {'symbol': symbol})
        return result

    def parse_order_status(self, status: Str) -> Str:
        """
 @ignore
        parses an exchange order status into a CCXT order status
        :param str status: exchange order status
        :returns str: a CCXT order status
        """
        statuses = {
            'open': 'open',
            'new': 'open',
            'partially-filled': 'open',
            'closed': 'closed',
            'filled': 'closed',
            'canceled': 'canceled',
            'filled-and-canceled': 'canceled',
            'done-for-day': 'expired',
            'rejected': 'rejected',
        }
        return self.safe_string(statuses, status, status)

    def parse_order(self, order: dict, market: Market = None) -> Order:
        """
 @ignore
        parses an exchange order into a CCXT order structure
        :param dict order: exchange order
        :param dict [market]: market structure
        :returns dict: a CCXT order structure
        """
        marketId = self.safe_string(order, 'pair')
        resolvedMarket = self.safe_market(marketId, market)
        amountString = self.safe_string(order, 'quantity')
        filledString = self.safe_string(order, 'filledQuantity')
        remainingString = None
        if (amountString is not None) and (filledString is not None):
            remainingString = Precise.string_sub(amountString, filledString)
        feeData = self.safe_dict(order, 'fee')
        fee = None
        if feeData is not None:
            feeCost = self.safe_number(feeData, 'amount')
            feeCurrency = self.safe_string_2(feeData, 'currency', 'symbol')
            if (feeCost is not None) or (feeCurrency is not None):
                fee = {
                    'cost': feeCost,
                    'currency': feeCurrency,
                }
        timestamp = self.parse8601(self.safe_string(order, 'createdAt'))
        lastTradeTimestamp = None
        if (filledString is not None) and Precise.string_gt(filledString, '0'):
            lastTradeTimestamp = self.parse8601(self.safe_string(order, 'executedAt'))
        orderType = self.safe_string_lower(order, 'type')
        if orderType == 'stoplimit':
            orderType = 'limit'
        elif orderType == 'stopmarket':
            orderType = 'market'
        return self.safe_order({
            'info': order,
            'id': self.safe_string(order, 'id'),
            'clientOrderId': None,
            'timestamp': timestamp,
            'datetime': self.iso8601(timestamp),
            'lastTradeTimestamp': lastTradeTimestamp,
            'lastUpdateTimestamp': self.parse8601(self.safe_string(order, 'updatedAt')),
            'status': self.parse_order_status(self.safe_string(order, 'status')),
            'symbol': resolvedMarket['symbol'],
            'type': orderType,
            'timeInForce': self.safe_string(order, 'timeInForce'),
            'postOnly': None,
            'side': self.safe_string_lower(order, 'side'),
            'price': self.safe_number(order, 'limitPrice'),
            'triggerPrice': self.safe_number(order, 'triggerPrice'),
            'cost': self.safe_number(order, 'filledAmount'),
            'amount': self.parse_number(amountString),
            'filled': self.parse_number(filledString),
            'remaining': self.parse_number(remainingString),
            'average': self.safe_number(order, 'filledAveragePrice'),
            'fee': fee,
            'trades': None,
        }, resolvedMarket)

    def fetch_order(self, id: str, symbol: Str = None, params={}) -> Order:
        """
        fetches information on an order made by the user

        https://docs.fusion.bitpanda.com/get-order-by-id-4203922e0

        :param str id: order id
        :param str [symbol]: unified market symbol
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: an order structure
        """
        self.load_markets()
        request = {
            'orderId': id,
        }
        response = self.privateGetV1AccountOrdersOrderId(self.extend(request, params))
        return self.parse_order(response)

    def fetch_orders(self, symbol: Str = None, since: Int = None, limit: Int = None, params={}) -> list[Order]:
        """
        fetches information on multiple orders made by the user

        https://docs.fusion.bitpanda.com/get-orders-4203921e0

        :param str [symbol]: unified market symbol
        :param int [since]: timestamp in ms of the earliest order
        :param int [limit]: the maximum number of orders to return
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :param int [params.until]: timestamp in ms of the latest order
        :param str [params.cursor]: cursor from the previous page
        :param str [params.status]: exchange order status filter
        :returns dict[]: a list of order structures
        """
        self.load_markets()
        request = {}
        market = None
        if symbol is not None:
            market = self.market(symbol)
            request['pair'] = market['id']
        if since is not None:
            request['startTime'] = self.parse_to_int(Precise.string_div(self.number_to_string(since), '1000'))
        if limit is not None:
            request['limit'] = limit
        until = self.safe_integer(params, 'until')
        if until is not None:
            request['endTime'] = self.parse_to_int(Precise.string_div(self.number_to_string(until), '1000'))
        params = self.omit(params, 'until')
        response = self.privateGetV1AccountOrders(self.extend(request, params))
        data = self.safe_list(response, 'data', [])
        return self.parse_orders(data, market, since, limit)

    def fetch_open_orders(self, symbol: Str = None, since: Int = None, limit: Int = None, params={}) -> list[Order]:
        """
        fetches information on currently open orders made by the user

        https://docs.fusion.bitpanda.com/get-orders-4203921e0

        :param str [symbol]: unified market symbol
        :param int [since]: timestamp in ms of the earliest order
        :param int [limit]: the maximum number of orders to return
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict[]: a list of order structures
        """
        return self.fetch_orders(symbol, since, limit, self.extend(params, {'status': 'open'}))

    def fetch_closed_orders(self, symbol: Str = None, since: Int = None, limit: Int = None, params={}) -> list[Order]:
        """
        fetches information on closed orders made by the user

        https://docs.fusion.bitpanda.com/get-orders-4203921e0

        :param str [symbol]: unified market symbol
        :param int [since]: timestamp in ms of the earliest order
        :param int [limit]: the maximum number of orders to return
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict[]: a list of order structures
        """
        return self.fetch_orders(symbol, since, limit, self.extend(params, {'status': 'closed'}))

    def create_market_order_with_cost(self, symbol: str, side: OrderSide, cost: float, params: dict = {}) -> Order:
        """
        create a market order by providing the symbol, side and cost in quote currency

        https://docs.fusion.bitpanda.com/create-order-4204526e0

        :param str symbol: unified symbol of the market to create an order in
        :param str side: 'buy' or 'sell'
        :param float cost: how much to trade in units of the quote currency
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: an order structure
        """
        request = {
            'cost': cost,
        }
        return self.create_order(symbol, 'market', side, 0, None, self.extend(request, params))

    def create_market_buy_order_with_cost(self, symbol: str, cost: float, params: dict = {}) -> Order:
        """
        create a market buy order by providing the symbol and cost in quote currency

        https://docs.fusion.bitpanda.com/create-order-4204526e0

        :param str symbol: unified symbol of the market to create an order in
        :param float cost: how much to trade in units of the quote currency
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: an order structure
        """
        return self.create_market_order_with_cost(symbol, 'buy', cost, params)

    def create_market_sell_order_with_cost(self, symbol: str, cost: float, params: dict = {}) -> Order:
        """
        create a market sell order by providing the symbol and cost in quote currency

        https://docs.fusion.bitpanda.com/create-order-4204526e0

        :param str symbol: unified symbol of the market to create an order in
        :param float cost: how much to trade in units of the quote currency
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: an order structure
        """
        return self.create_market_order_with_cost(symbol, 'sell', cost, params)

    def create_order(self, symbol: str, type: OrderType, side: OrderSide, amount: float, price: Num = None, params={}) -> Order:
        """
        create a market, limit, stop-market or stop-limit order

        https://docs.fusion.bitpanda.com/create-order-4204526e0

        :param str symbol: unified symbol of the market to create an order in
        :param str type: 'market' or 'limit'
        :param str side: 'buy' or 'sell'
        :param float amount: how much to trade in units of the base currency
        :param float [price]: the price at which the order is to be fulfilled, in units of the quote currency
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :param float [params.cost]: quote-currency amount; mutually exclusive with the base-currency amount argument
        :param float [params.amount]: exchange-specific alias for params.cost
        :param float [params.triggerPrice]: price at which a stop order is triggered
        :param float [params.stopPrice]: alias for params.triggerPrice
        :param str [params.timeInForce]: 'GTC', 'GTD', 'IOC' or 'FOK'
        :param str [params.endTime]: ISO 8601 expiry timestamp, required when timeInForce is 'GTD'
        :returns dict: an order structure
        """
        self.load_markets()
        market = self.market(symbol)
        orderType = type.lower()
        orderSide = side.lower()
        if (orderType != 'limit') and (orderType != 'market'):
            raise NotSupported(self.id + ' createOrder() supports market and limit orders, with an optional triggerPrice for stop orders')
        if (orderSide != 'buy') and (orderSide != 'sell'):
            raise InvalidOrder(self.id + ' createOrder() side must be buy or sell')
        clientOrderId = self.safe_string_2(params, 'clientOrderId', 'client_order_id')
        if clientOrderId is not None:
            raise NotSupported(self.id + ' createOrder() does not support clientOrderId')
        triggerPrice = self.safe_string_2(params, 'triggerPrice', 'stopPrice')
        request = {
            'pair': market['id'],
            'side': self.capitalize(orderSide),
            'type': self.capitalize(orderType),
        }
        cost = self.safe_string_2(params, 'cost', 'amount')
        if cost is None:
            request['quantity'] = self.amount_to_precision(symbol, amount)
        else:
            request['amount'] = self.cost_to_precision(symbol, cost)
        if orderType == 'limit':
            if price is None:
                raise InvalidOrder(self.id + ' createOrder() requires a price for limit orders')
            request['limitPrice'] = self.price_to_precision(symbol, price)
        if triggerPrice is not None:
            request['type'] = 'Stop' + self.capitalize(orderType)
            request['triggerPrice'] = self.price_to_precision(symbol, triggerPrice)
        timeInForce = self.safe_string_upper(params, 'timeInForce')
        if timeInForce is not None:
            request['timeInForce'] = timeInForce
        params = self.omit(params, ['clientOrderId', 'client_order_id', 'triggerPrice', 'stopPrice', 'timeInForce', 'cost', 'amount'])
        response = self.privatePostV1AccountOrders(self.extend(request, params))
        return self.parse_order(response, market)

    def cancel_order(self, id: str, symbol: Str = None, params={}) -> Order:
        """
        cancels an open order

        https://docs.fusion.bitpanda.com/cancel-order-by-id-4203923e0

        :param str id: order id
        :param str [symbol]: unified market symbol
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: an order structure
        """
        self.load_markets()
        request = {
            'orderId': id,
        }
        response = self.privateDeleteV1AccountOrdersOrderId(self.extend(request, params))
        return self.parse_order(response)

    def parse_trade(self, trade: dict, market: Market = None) -> Trade:
        """
 @ignore
        parses an exchange trade into a CCXT trade structure
        :param dict trade: exchange trade
        :param dict [market]: market structure
        :returns dict: a CCXT trade structure
        """
        marketId = self.safe_string(trade, 'pair')
        resolvedMarket = self.safe_market(marketId, market)
        timestamp = self.parse8601(self.safe_string(trade, 'executedAt'))
        feeData = self.safe_dict(trade, 'fee')
        fee = None
        if feeData is not None:
            fee = {
                'cost': self.safe_number(feeData, 'amount'),
                'currency': self.safe_string_2(feeData, 'currency', 'symbol'),
            }
        return self.safe_trade({
            'info': trade,
            'id': self.safe_string(trade, 'id'),
            'order': self.safe_string(trade, 'orderId'),
            'timestamp': timestamp,
            'datetime': self.iso8601(timestamp),
            'symbol': resolvedMarket['symbol'],
            'type': None,
            'side': self.safe_string_lower(trade, 'side'),
            'takerOrMaker': None,
            'price': self.safe_number(trade, 'price'),
            'amount': self.safe_number_2(trade, 'quantity', 'amount'),
            'cost': self.safe_number_2(trade, 'totalAmount', 'total'),
            'fee': fee,
        }, resolvedMarket)

    def fetch_my_trades(self, symbol: Str = None, since: Int = None, limit: Int = None, params={}) -> list[Trade]:
        """
        fetches all trades made by the user

        https://docs.fusion.bitpanda.com/get-trades-4203920e0

        :param str [symbol]: unified market symbol
        :param int [since]: timestamp in ms of the earliest trade
        :param int [limit]: the maximum number of trades to return
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :param int [params.until]: timestamp in ms of the latest trade
        :param str [params.cursor]: cursor from the previous page
        :param str [params.orderId]: filter by exchange order id
        :returns dict[]: a list of trade structures
        """
        self.load_markets()
        request = {}
        market = None
        if symbol is not None:
            market = self.market(symbol)
            request['pair'] = market['id']
        if since is not None:
            request['startTime'] = self.parse_to_int(Precise.string_div(self.number_to_string(since), '1000'))
        if limit is not None:
            request['limit'] = limit
        until = self.safe_integer(params, 'until')
        if until is not None:
            request['endTime'] = self.parse_to_int(Precise.string_div(self.number_to_string(until), '1000'))
        params = self.omit(params, 'until')
        response = self.privateGetV1AccountTrades(self.extend(request, params))
        data = self.safe_list(response, 'data', [])
        return self.parse_trades(data, market, since, limit)

    def sign(self, path: str, api: str = 'public', method: str = 'GET', params={}, headers: dict = None, body: Str = None):
        """
 @ignore
        signs an API request using the required x-api-key header
        :returns dict: signed request
        """
        self.check_required_credentials()
        baseUrl = self.urls['api'][api]
        url = baseUrl + '/' + self.implode_params(path, params)
        query = self.omit(params, self.extract_params(path))
        requestHeaders = {
            'Accept': 'application/json',
            'x-api-key': self.apiKey,
        }
        if headers is not None:
            requestHeaders = self.extend(requestHeaders, headers)
        if method == 'POST':
            requestHeaders['Content-Type'] = 'application/json'
            body = self.json(query)
        elif self.is_empty(query) is False:
            url += '?' + self.urlencode(query)
        return {'url': url, 'method': method, 'body': body, 'headers': requestHeaders}

    def handle_errors(self, statusCode: int, statusText: str, url: str, method: str, responseHeaders: dict, responseBody: str, response: object, requestHeaders: object, requestBody: object):
        """
 @ignore
        handles HTTP errors returned by Bitpanda Fusion
        :returns void:
        """
        if statusCode < 400:
            return None
        if statusCode == 422:
            if (method == 'POST') and (url.find('/v1/account/orders') >= 0):
                raise InvalidOrder(self.id + ' ' + responseBody)
        elif statusCode == 404:
            if url.find('/v1/account/orders/') >= 0:
                raise OrderNotFound(self.id + ' ' + responseBody)
            if (url.find('/v1/orderbook/') >= 0) or (url.find('/v1/candles/') >= 0):
                raise BadSymbol(self.id + ' ' + responseBody)
        return None
